AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for sam-app

Parameters:
  JobTimeout:
    Type: Number
    Default: 180
    Description: The maximum amount of time (in seconds) for the job to run.

Globals:
  Function:
    Timeout: 10
    Tracing: Active
Resources:
  SearchEmbeddingsFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Role: arn:aws:iam::207567786658:role/AppLambdaExecutionRole
      Timeout: !Ref JobTimeout
      FunctionName: "search-embeddings-func"
      MemorySize: 2048
    Metadata:
      DockerBuildTarget: prod
      Dockerfile: Dockerfile
      DockerContext: ./search_embeddings_app
      DockerTag: python3.10-v1

  SearchEmbeddingsFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      AuthType: NONE
      TargetFunctionArn: !GetAtt SearchEmbeddingsFunction.Arn
      Cors:
        AllowOrigins:
          - "*"
        AllowMethods:
          - "GET"

  # Lambda Functionのアクセス許可を設定
  SearchEmbeddingsFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunctionUrl
      FunctionName: !GetAtt SearchEmbeddingsFunction.Arn
      Principal: "*"
      FunctionUrlAuthType: NONE